<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="additionService"
     targetNamespace="http://xmlns.oracle.com/mypractice/additionBPEL/wsdl/additionService"
     xmlns:tns="http://xmlns.oracle.com/mypractice/additionBPEL/wsdl/additionService"
     xmlns:inp1="http://www.schemaaddition.com"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://www.schemaaddition.com" schemaLocation="../Schemas/addition.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="requestMessage">
        <wsdl:part name="part1" element="inp1:request"/>
    </wsdl:message>
    <wsdl:message name="replyMessage">
        <wsdl:part name="part1" element="inp1:response"/>
    </wsdl:message>
    <wsdl:portType name="execute_ptt">
        <wsdl:operation name="execute">
            <wsdl:input message="tns:requestMessage"/>
            <wsdl:output message="tns:replyMessage"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
