<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="additionService"
     targetNamespace="http://xmlns.oracle.com/mypractice/additionBPEL/wsdl/additionService"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="http://xmlns.oracle.com/mypractice/additionBPEL/wsdl/additionService"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="additionBPEL">
        <plnk:role name="execute_ptt" portType="tns:execute_ptt"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://xmlns.oracle.com/mypractice/additionBPEL/wsdl/additionService"
         location="additionService.wsdl"/>
</wsdl:definitions>
