<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="distributedtrancationBPEL"
     targetNamespace="http://xmlns.oracle.com/mypractice/distributedTrancation/distributedtrancationBPEL"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:client="http://xmlns.oracle.com/mypractice/distributedTrancation/distributedtrancationBPEL"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:ns1="http://schemas.oracle.com/bpel/extension"
    >
    <plnk:partnerLinkType name="distributedtrancationBPEL">
        <plnk:role name="distributedtrancationBPELProvider" portType="client:distributedtrancationBPEL"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://schemas.oracle.com/bpel/extension" location="RuntimeFault.wsdl"/>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/mypractice/distributedTrancation/distributedtrancationBPEL"
                 schemaLocation="../Schemas/distributedtrancationBPEL.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="distributedtrancationBPELRequestMessage">
        <wsdl:part name="payload" element="client:process"/>
    </wsdl:message>
    <wsdl:message name="distributedtrancationBPELResponseMessage">
        <wsdl:part name="payload" element="client:processResponse"/>
    </wsdl:message>
    <wsdl:portType name="distributedtrancationBPEL">
        <wsdl:operation name="process">
            <wsdl:input message="client:distributedtrancationBPELRequestMessage"/>
            <wsdl:output message="client:distributedtrancationBPELResponseMessage"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
